import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Provider from "@/components/Provider";


import "react-loading-skeleton/dist/skeleton.css"
import Wrapper from "@/components/Wrapper";
import { Providers } from "./providers";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className="light" suppressHydrationWarning >
      <body className="bg-veryLightGrayBg dark:bg-veryDarkBlueBg">
        <Providers>
          
        <Navbar/>

         <Provider>
           <Wrapper >
       
            {children}
          </Wrapper>

        </Provider>
        </Providers>

      </body>
    </html>
  );
}
